// measure
export const CHANGE_NOTE = 'CHANGE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const INSERT_NOTE = 'INSERT_NOTE';
export const TOGGLE_NOTE_DOTTED = 'TOGGLE_NOTE_DOTTED';
export const TOGGLE_NOTE_TREMOLO = 'TOGGLE_NOTE_TREMOLO';
export const TOGGLE_NOTE_VIBRATO = 'TOGGLE_NOTE_VIBRATO';
export const TOGGLE_NOTE_TRILL = 'TOGGLE_NOTE_TRILL';
export const CHANGE_NOTE_LENGTH = 'CHANGE_NOTE_LENGTH';
export const INCREASE_NOTE_LENGTH = 'INCREASE_NOTE_LENGTH';
export const DECREASE_NOTE_LENGTH = 'DECREASE_NOTE_LENGTH';
export const COPY_NOTE = 'COPY_NOTE';
export const CUT_NOTE = 'CUT_NOTE';
export const PASTE_NOTE = 'PASTE_NOTE';
export const ADD_REPEAT_END = 'ADD_REPEAT_END';

//track
export const REPLACE_SONG = 'REPLACE_SONG';
export const INSERT_MEASURE = 'INSERT_MEASURE';
export const DELETE_MEASURE = 'DELETE_MEASURE';
export const CHANGE_TIME_SIGNATURE = 'CHANGE_TIME_SIGNATURE';
export const CHANGE_BPM = 'CHANGE_BPM';
export const CHANGE_TUNING = 'CHANGE_TUNING';

// tracks
export const INSERT_TRACK = 'INSERT_TRACK';
export const DELETE_TRACK = 'DELETE_TRACK';
export const SELECT_TRACK = 'SELECT_TRACK';
export const RESIZE = 'RESIZE';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';

// playingIndex
export const SET_PLAYING_INDEX = 'SET_PLAYING_INDEX';
export const ADVANCE_PLAYING_INDEX = 'ADVANCE_PLAYING_INDEX';
export const TOGGLE_METRONOME = 'TOGGLE_METRONOME';

// cursor
export const SET_CURSOR = 'SET_CURSOR';
export const MOVE_CURSOR_LEFT = 'MOVE_CURSOR_LEFT';
export const MOVE_CURSOR_RIGHT = 'MOVE_CURSOR_RIGHT';
export const MOVE_CURSOR_UP= 'MOVE_CURSOR_UP';
export const MOVE_CURSOR_DOWN = 'MOVE_CURSOR_DOWN';

// instrument
export const SET_INSTRUMENT = 'SET_INSTRUMENT';
