export const CHANGE_NOTE = 'CHANGE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_MEASURE = 'DELETE_MEASURE';
export const INSERT_MEASURE = 'INSERT_MEASURE';
export const CHANGE_NOTE_LENGTH = 'CHANGE_NOTE_LENGTH';
export const INSERT_NOTE = 'INSERT_NOTE';
export const CHANGE_TIME_SIGNATURE = 'CHANGE_TIME_SIGNATURE';
export const TOGGLE_NOTE_DOTTED = 'TOGGLE_NOTE_DOTTED';
export const TOGGLE_NOTE_TREMOLO = 'TOGGLE_NOTE_TREMOLO';
export const REPLACE_SONG = 'REPLACE_SONG';
export const CHANGE_TUNING = 'CHANGE_TUNING';
export const COPY_NOTE = 'COPY_NOTE';
export const CUT_NOTE = 'CUT_NOTE';
export const PASTE_NOTE = 'PASTE_NOTE';
export const CHANGE_BPM = 'CHANGE_BPM';
export const RESIZE = 'RESIZE';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';

// playingNote
export const SET_PLAYING_NOTE = 'SET_PLAYING_NOTE';
export const ADVANCE_PLAYING_NOTE = 'ADVANCE_PLAYING_NOTE';

// cursor
export const SET_CURSOR = 'SET_CURSOR';
export const MOVE_CURSOR_LEFT = 'MOVE_CURSOR_LEFT';
export const MOVE_CURSOR_RIGHT = 'MOVE_CURSOR_RIGHT';
export const MOVE_CURSOR_UP= 'MOVE_CURSOR_UP';
export const MOVE_CURSOR_DOWN = 'MOVE_CURSOR_DOWN';
